server {
    server_name nnquangdev.id.vn www.nnquangdev.id.vn 36.50.176.64 _;

    client_max_body_size 25M;

    root /var/www/marketlink/frontend;
    index index.html;

    # phpMyAdmin giao diện Web quản lý MySQL
    location /phpmyadmin {
        root /var/www;
        index index.php index.html index.htm;
        location ~ ^/phpmyadmin/(.+\.php)$ {
            try_files $uri =404;
            root /var/www;
            fastcgi_pass unix:/run/php/php8.1-fpm.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
        location ~* ^/phpmyadmin/(.+\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt))$ {
            root /var/www;
        }
    }

    # Nginx trực tiếp phục vụ các tệp ảnh tĩnh đã upload
    location /uploads/ {
        alias /var/www/marketlink/uploads/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
        access_log off;
    }

    # Chuyển tiếp các yêu cầu API sang Spring Boot Backend
    location /api/ {
        proxy_pass http://127.0.0.1:8081/api/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Hỗ trợ Real-time SSE cho AI Assistant Chatbot & Notification Stream
        proxy_set_header Connection '';
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 300s;
        proxy_connect_timeout 60s;
    }

    # Single Page Application React Router
    location / {
        try_files $uri $uri/ /index.html;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/nnquangdev.id.vn/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/nnquangdev.id.vn/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.nnquangdev.id.vn) {
        return 301 https://$host$request_uri;
    }

    if ($host = nnquangdev.id.vn) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name nnquangdev.id.vn www.nnquangdev.id.vn 36.50.176.64 _;
    return 301 https://$host$request_uri;
}
